from eth_account import Account  #Importing Account from the eth_account module of Web3.py
import secrets

class Account():
    def __init__(self, priv_key, walletID):
        self.priv_key = priv_key
        self.walletID = walletID

    private = secrets.token_hex(32)  #Generating a random hexadecimal string of 32 bytes
    priv_key = "0x" + private
    print ("Private key:", priv_key)

#create wallet ID
    for arrayitem in range(3):
        global Wallet
        addr = Account.from_key(priv_key) # Creating a new account using the private_key and storing it in variable addr.
        while arrayitem < 3: # While loop has been introduced to test and prove that no more than one address can be generated by one private key.
            arrayitem += 1
            print(({arrayitem}), "Wallet ID:", addr.address)
        break





# Balance Object.

# 1. This Certificate Management System is used to simply manage certificate and not carry out any financial transactions.
# 2. However, wallet is required for key storage.
# 3. This program will  therefore not have a function to calculate balance in the wallet.








